// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ProposalTypes$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ProposalTypes";
  readonly sourceName: "contracts/contracts/ProposalTypes.sol";
  readonly abi: [];
  readonly bytecode: "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212203450fcba3d146ee0f0abd1158f3091c1a699a58cac3bc7d9d711c5fecf83f22e64736f6c634300081c0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212203450fcba3d146ee0f0abd1158f3091c1a699a58cac3bc7d9d711c5fecf83f22e64736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/contracts/ProposalTypes.sol";
  readonly buildInfoId: "solc-0_8_28-13bfda84e5368606e7ec519263c7d71c11f02007";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ProposalTypes"]: ProposalTypes$Type;
    ["contracts/contracts/ProposalTypes.sol:ProposalTypes"]: ProposalTypes$Type;
  }
}